---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.10-alpine
  commands:
    - pip install -r requirements.txt 
    - pytest
- name: bandit
  image: python:3.10-alpine
  commands:
     - pip install -r requirements.txt
     - pip install bandit
     - bandit -r calc
